name = "EngEconomics"
uuid = "94405613-731d-4cda-ae3f-11a428ef51fb"
authors = ["Zach Bortoff <zbortoff@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
